-- Seed data update (2026-09 audit): "Deputy Chief Minister Vijay Sharma" (Chhattisgarh) was
-- matching the Chief Minister rule. The rule now ignores "deputy ..." and more unrelated Vijays
-- are negative signals. Only rows still holding the previously seeded pattern are changed.

UPDATE relevance_rules SET pattern = '(?<!deputy )\b(chief minister|cm) (c )?(joseph )?vijay\b(?! (sethupathi|antony|devarakonda|deverakonda|varma|raaz|raz|mallya|rupani|shankar|hazare|sinha|wadettiwar|vasanth|yesudas|prakash|kumar|shekhar|goel|chowk|nagar|singh|bahuguna|mishra|patil|babu|milton|kedia|amritraj|mahajan|jolly|sai|sales|bank|bhaskar|raghavan|thakur|chouhan|chauhan|dahiya|kiragandur|salgaonkar|sampla|oberoi|rathore|yadav|gupta|mehta|malhotra|patel|chaudhary|chaudhry|sardesai|tendulkar|kichlu|diwas|hazaribagh|sharma|bahadur|mallik|pal)\b)', updated_at = now()
 WHERE name = 'chief-minister-vijay' AND pattern = '\b(chief minister|cm) (c )?(joseph )?vijay\b(?! (sethupathi|antony|devarakonda|deverakonda|varma|raaz|raz|mallya|rupani|shankar|hazare|sinha|wadettiwar|vasanth|yesudas|prakash|kumar|shekhar|goel|chowk|nagar|singh|bahuguna|mishra|patil|babu|milton|kedia|amritraj|mahajan|jolly|sai|sales|bank|bhaskar|raghavan|thakur|chouhan|chauhan|dahiya|kiragandur|salgaonkar|sampla|oberoi|rathore|yadav|gupta|mehta|malhotra|patel|chaudhary|chaudhry|sardesai|tendulkar|kichlu|diwas|hazaribagh)\b)';

UPDATE relevance_rules SET pattern = '\bvijay (sethupathi|antony|devarakonda|deverakonda|varma|raaz|raz|mallya|rupani|shankar|hazare|sinha|wadettiwar|vasanth|yesudas|prakash|kumar|shekhar|goel|chowk|nagar|singh|bahuguna|mishra|patil|babu|milton|kedia|amritraj|mahajan|jolly|sai|sales|bank|bhaskar|raghavan|thakur|chouhan|chauhan|dahiya|kiragandur|salgaonkar|sampla|oberoi|rathore|yadav|gupta|mehta|malhotra|patel|chaudhary|chaudhry|sardesai|tendulkar|kichlu|diwas|hazaribagh|sharma|bahadur|mallik|pal)\b', updated_at = now()
 WHERE name = 'other-vijays' AND pattern = '\bvijay (sethupathi|antony|devarakonda|deverakonda|varma|raaz|raz|mallya|rupani|shankar|hazare|sinha|wadettiwar|vasanth|yesudas|prakash|kumar|shekhar|goel|chowk|nagar|singh|bahuguna|mishra|patil|babu|milton|kedia|amritraj|mahajan|jolly|sai|sales|bank|bhaskar|raghavan|thakur|chouhan|chauhan|dahiya|kiragandur|salgaonkar|sampla|oberoi|rathore|yadav|gupta|mehta|malhotra|patel|chaudhary|chaudhry|sardesai|tendulkar|kichlu|diwas|hazaribagh)\b';
